[package]
name = "sample-vaultrs-app"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
base64 = "0.21"
dotenv = "0.15"
hex = "0.4"
tokio = { version = "1", features = ["full"] }
vaultrs = { version = "0.7.3" }


