[package]
name = "sample-vaultrs-app"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
vaultrs = { version = "0.7.3" }
async-trait = "0.1"
hex = "0.4"
